language: cpp
compiler:
- gcc
os:
- linux
script:
- pushd MVMFirmwareUnitTests
- make
- popd
- ruby MVMFirmwareUnitTests/mvm_fw_test_run_scenarios.rb
- git remote remove origin
- git remote add origin  https://${GH_TOKEN}@github.com/fmselab/mvm-firmware.git
- git remote show origin
- mv scenarios/README.md README.md.SAVE
- git checkout master
- mv README.md.SAVE scenarios/README.md 
- "git commit --message \"Travis build+test run: $TRAVIS_BUILD_NUMBER [ci skip]\" scenarios/README.md"
- git push --quiet origin master
deploy:
  provider: s3
  access_key_id: 21W3LO10AM9USM38MVV5
  secret_access_key: Shb8jXu2A0pw92yVp9CgSV4ypfow4m40BmAe6Xs3
  endpoint: https://rgw.fisica.unimi.it
  bucket: fwtartifacts
  skip_cleanup: true
  local_dir: scenarios
env:
  global:
    secure: iQgXbtDikw0mj7LuZwexwRS5+cyiTLJ500TMk3YmP6RXr7eGszzKDmD18Ei0f1GiLoO2m8b7DM9ESyMk0rNm2XLujEKLmcWPOJUrXg0gKeo40BfmaP4oOPq1+aBmO1qK8q/U9vJjm3tUz3DWSk2e6LgTVzwdo/jTh2dEFlmXXF+cfNL2mdJpgsYCMFqhKSovy6w8QmCEYBvw30nTBE7RX/1RUW2/lbcMXvVs7ZGXeGgV+DLx4KrvSWugS/b5aeZ1PKA17yijMueow47ka1GnYAui2HEa3EK8aLRPA6clXW2vHJt1VVRtcdbmP2pCD4YCqUfPbukH1WHhWvdV0P7wNLluYBg4y4lEoh43PGxFWYja1mhxKwALz3iCw3ZPDsGixnyKj2b1oz1SKIt3CyOVxn4bc9ydlS5TBeaxJfe7TqvC4oeDaYD2lrpG2BxCrXSHlsvJo6HvCDF1/CylezpYbvGeix0bvWXysZ66urCvfNrjYHW1+dn7+iAahwZ3xgcav1pgXbS9IaZEkuDHF1mV02/pzFRrebD4kVEXI3kv3m0UVLyT+p03Nlg7tdKCjLIDccskCLUTAiJBijWPN1RWx9vHnrXIJ4oDPGYLOb0dD7TmIEMHH9//93nFzzTIzH2uh39xyzXDYOgdqpDl+dUBlYwwSz6jnLBH37ORu1EgQMg=

