language: cpp
compiler:
 - gcc
os:
 - linux

script:
 - cd MVMFirmwareUnitTests
 - make

deploy:
  provider: s3
  access_key_id: "21W3LO10AM9USM38MVV5"
  secret_access_key: "Shb8jXu2A0pw92yVp9CgSV4ypfow4m40BmAe6Xs3"
  endpoint: https://rgw.fisica.unimi.it
  bucket: "fwtartifacts"
  file:
    - "mvm_fw_unit_test_run"

